### ISSUE TITLE
Lab 3 notes

### ISSUE THREAD

**Issue by AntonC9018** [zzzzzzqwe/i2302gachayevdmitrii_uni#2]

**Comment by AntonC9018** [comment]
https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/40814d45f7694fd3989cf844ac162ee07ce51b70/Lab3/Example%202.md?plain=1#L74
Задай их.

2 часть не закончил.

**Comment by zzzzzzqwe** [comment]
С 11 пунктом вроде разобрался, исправьте если не так понял.
Сделал 2 часть.
Пункт 2.2 расписал в файле stack_2_explained.cpp в конце.

**Comment by AntonC9018** [comment]
https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/31c9a61423d81b5752a9af3c3b13d4e539dfab44/Lab3/stack_2_explained.cpp#L50
Не либо. Это сравнивает конкретно адреса.
Я не уверен если ты понял смысл. Перечитай, как выделяется память локальным переменны при вызове функций.

https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/31c9a61423d81b5752a9af3c3b13d4e539dfab44/Lab3/Example%202.md?plain=1#L74
Без оптимизаций скомпилируется столько копий, сколько определений. Определения в обоих файлах есть, то есть 2 копии.

**Comment by zzzzzzqwe** [comment]
> Не либо. Это сравнивает конкретно адреса.
> Я не уверен если ты понял смысл. Перечитай, как выделяется память локальным переменны при вызове функций.

Перечитал, разобрался. В данном случае при сравнении выведется 0, потому что указатели указывают на один и тот же адрес памяти.



> Без оптимизаций скомпилируется столько копий, сколько определений. Определения в обоих файлах есть, то есть 2 копии.

Понял, спасибо
