### ISSUE TITLE
Lab 4 Notes

### ISSUE THREAD

**Issue by AntonC9018** [zzzzzzqwe/i2302gachayevdmitrii_uni#3]
https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/496ac79d264bbc199d5b5231a4caab8ba002fd42/Lab4/dynamicArray.cpp#L21
Тут баг. Если изначальный размер дать 0 (что приемлемо), тут сломается все. Добавь тест под это.

https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/496ac79d264bbc199d5b5231a4caab8ba002fd42/Lab4/dynamicArray.cpp#L38
Можно еще вот так (более С++-но) `{arr->data, arr->length}`.

https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/496ac79d264bbc199d5b5231a4caab8ba002fd42/Lab4/dynamicArray.cpp#L43
Не обнуляй, пусть крашится при попытке повторно удалить. Двойное удаление это очень серьезный баг, который нужно обнаруживать сразу. В твоем случае, двойное удаление проигнорится.

Добавь команду, которой компилируешь, в папку с лабой. Либо bat, либо sh скрипт.

**Comment by AntonC9018** [comment]
А и еще в конце есть про инкапсуляцию. Ответь своими словами, как понимаешь (если понимаешь)

**Comment by zzzzzzqwe** [comment]
https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/e0678d4901793b8450364ea678daf860ba6e23c3/Lab4/fullCode.cpp#L28-L29

Добавил проверку на нулевой capacity

https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/e0678d4901793b8450364ea678daf860ba6e23c3/Lab4/fullCode.cpp#L108-L115

Добавил тест проверяющий работу случая с 0 capacity

https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/e0678d4901793b8450364ea678daf860ba6e23c3/Lab4/fullCode.cpp#L48

Тут поменял

https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/069b281973fd5d86e1e4738c188804cd1b798648/Lab4/fullCode.cpp#L52-L56

Убрал обнуление

Насчет инкапсуляции, не видел что там еще 3 часть есть.
1. В коде инкапсулированы данные в структуре DynamicArray. Они закрыты внутри структуры и доступны только через функции.
Операции над массивом также инкапсулированы в функции. Например, создание массива, добавление элементов, доступ к элементу по индексу и тд - все операции выполняются через функции скрывая детали реализации.
2. Насколько я понимаю, интерфейс определяет каким образом внешний код может взаимодействовать с объектом, а инкапсуляция реализует интерфейс, предоставляя доступ к внутренним данным объекта или класса ,скрывая их детали реализации.

Еще вы не просмотрели исправления в 3 лабе, напоминаю если вдруг случайно пропустили

**Comment by AntonC9018** [comment]
https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/e0678d4901793b8450364ea678daf860ba6e23c3/Lab4/fullCode.cpp#L48
`std::span<int>` тоже не обязательно, он это из возвращаемого типа понимает.

И батник не добавил для компиляции. Но ты компилируешь через `fullCode` я так понял.

**Comment by zzzzzzqwe** [comment]
Убрал `std::span<int>`
Батник добавил вроде 
https://github.com/zzzzzzqwe/i2302gachayevdmitrii_uni/blob/31c9a61423d81b5752a9af3c3b13d4e539dfab44/Lab4/compile.bat#L1

**Comment by AntonC9018** [comment]
Этот батник не скопилирует, больше чем уверен. Добавь флаг `-std=c++20`. Спаны из C++20

**Comment by zzzzzzqwe** [comment]
Флаг нужно добавлять в tasks.json? Добавил и все равно спаны не поддерживаются. До этого приходилось юзать онлайн компилятор

**Comment by AntonC9018** [comment]
> Флаг нужно добавлять в tasks.json? Добавил и все равно спаны не поддерживаются. До этого приходилось юзать онлайн компилятор

В батник которым компилируешь. `.vscode` перекопируй у меня более новый, я его поправлял чуток
